#ifndef PYPREFERENCE_H__
#define PYPREFERENCE_H__

enum
{
	BOGHMA_PYPREFERENCE_MAIN_GROUP						= 999,	
	BOGHMA_PYPREFERENCE_SHOW_IN_TOPMENU					= 1000,
	BOGHMA_PYPREFERENCE_UPDATE_GROUP					= 1001,
	BOGHMA_PYPREFERENCE_CHECK_SOURCE 					= 1002,
	BOGHMA_PYPREFERENCE_UPDATE_FROM			 			= 1003,
		BOGHMA_PYPREFERENCE_UPDATE_GITHUB 			= 0,
		BOGHMA_PYPREFERENCE_UPDATE_GITEE 			= 1,
	BOGHMA_PYPREFERENCE_TIME_INTERVAL					= 1004,


	PYPREFERENCE_DUMMY
};

#endif // PYPREFERENCE_H__
