CONTAINER pypreference
{
	NAME pypreference;

	GROUP
	{
		SEPARATOR BOGHMA_PYPREFERENCE_MAIN_GROUP { }
		GROUP
		{
		DEFAULT 1;
		BOOL BOGHMA_PYPREFERENCE_SHOW_IN_TOPMENU { ANIM OFF; }
		// FILENAME PYPREFERENCE_FILE_TEST {ANIM OFF; DIRECTORY;}
		}
		SEPARATOR BOGHMA_PYPREFERENCE_UPDATE_GROUP { }
		GROUP
		{	
			GROUP
			{
				DEFAULT 1;
				//COLUMNS 1;

				BOOL BOGHMA_PYPREFERENCE_CHECK_SOURCE			{ ANIM OFF; }
				LONG BOGHMA_PYPREFERENCE_UPDATE_FROM
				{
					CUSTOMGUI QUICKTABRADIO;
					CYCLE
					{
						BOGHMA_PYPREFERENCE_UPDATE_GITHUB;
						BOGHMA_PYPREFERENCE_UPDATE_GITEE;
					}	
				}	
				LONG BOGHMA_PYPREFERENCE_TIME_INTERVAL		{ MIN 1; MAX 10; }
				
			}
		}

	}
}
